name: CI

on:
  push:
    branches:
      - main # Trigger the workflow on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t my-flask-app:latest .

      - name: Log in to Docker Hub
        run: echo "Awsedrft@456" | docker login -u "bhanutejadev" --password-stdin

      - name: Push Docker image
        run: docker push my-flask-app:latest
